Husnain/hawqal GitHub action
CapregSoft/Hawqal-python pull request #2
Opened 2022-12-22 05:25 UTC by husnain9

I implemented github actions for hawqal-python repository
Ticket name : Implemented Github action
Ticket link : https://app.clickup.com/t/86695kwhy

2022-12-22 05:38 UTC, AhmedSaleemKhan requested changes

2022-12-22 05:38 UTC, AhmedSaleemKhan commented on .github/workflows/example.yml
> +on: [push]
Do it will build all the pushes to master or to local branch?

2022-12-22 05:38 UTC, AhmedSaleemKhan commented on .github/workflows/example.yml
> +
Change the file name from example.yml to hawqal-python.yml

2022-12-27 09:23 UTC, AhsanYousaf approved these changes

2022-12-27 09:23 UTC, merged